spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Ejemplo1
    username: postgres
    password: su-clave
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

